default_install_hook_types: [pre-commit]

repos:
  - repo: builtin
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: check-json
      - id: check-yaml
      - id: mixed-line-ending
      - id: check-symlinks
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.21.0
    hooks:
      - id: markdownlint-cli2
        name: markdownlint
