name: Codespell

on:
  push:
  workflow_call:
    inputs:
      path:
        description: 'Path to check'
        type: string
        default: .
      skip:
        description: 'Files to skip'
        type: string
      ignore_words_file:
        description: 'File containing words to ignore'
        type: string

jobs:
  codespell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          show-progress: false

      - name: Use Codespell
        uses: codespell-project/actions-codespell@v2.1
        with:
          path: ${{ inputs.path }}
          skip: ${{ inputs.skip }}
          ignore_words_file: ${{ inputs.ignore_words_file }}
          check_hidden: true
          check_filenames: true
