name: Format

on: workflow_call

concurrency: ${{ github.workflow }}-${{ github.ref }}
env:
  BRANCH: ${{ github.head_ref || github.ref_name }}
  PATCH_NAME: format.patch
  ARTIFACT_NAME: format-patch

jobs:
  format:
    runs-on: ubuntu-slim
    outputs:
      patched: ${{ steps.patch.outputs.patched }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          show-progress: false
          persist-credentials: false
          ref: ${{ env.BRANCH }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7.6.0

      - name: Fix lints
        run: uvx ruff check --diff || uvx ruff check --fix --quiet

      - name: Fix format
        run: uvx ruff format --diff || uvx ruff format --quiet

      - name: Create format patch
        id: patch
        run: echo "patched=$(git diff | tee "$PATCH_NAME" | head -c1)" > "$GITHUB_OUTPUT"

      - name: Upload artifact
        if: steps.patch.outputs.patched
        uses: actions/upload-artifact@v7.0.0
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.PATCH_NAME }}

  push:
    if: needs.format.outputs.patched
    needs: format
    runs-on: ubuntu-slim
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          show-progress: false
          ref: ${{ env.BRANCH }}

      - name: Download artifact
        uses: actions/download-artifact@v8.0.1
        with:
          pattern: ${{ env.ARTIFACT_NAME }}

      - name: Set Git config
        run: |
          git config user.email github-actions[bot]@users.noreply.github.com
          git config user.name github-actions[bot]

      - name: Commit changes
        run: |
          git apply "$PATCH_NAME" || true
          git commit -m "style: format scripts" || true
          git pull --rebase origin "$BRANCH"
          git push origin "HEAD:$BRANCH"
