name: Format

on: workflow_call

concurrency: ${{ github.job }}-${{ github.ref }}

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.5
        with:
          show-progress: false

      - name: Setup Biome
        uses: biomejs/setup-biome@v2.1.1
        with:
          version: latest

      - name: Run Biome
        run: biome check --apply .

      - name: Set Git config
        run: |
          git config user.email github-actions[bot]@users.noreply.github.com
          git config user.name github-actions[bot]

      - name: Commit changes
        run: |
          git add .
          git commit -m "style: format scripts" || exit 0
          git pull --rebase --autostash
          git push
