name: Format

on: workflow_call

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.2
        with:
          show-progress: false

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1.2.1
        with:
          bun-version: latest

      - name: Install node dependencies
        run: bun install --frozen-lockfile

      - name: Fix lints
        run: bun lint --fix

      - name: Format with Prettier
        run: bun prettier --write **.ts

      - name: Set Git config
        run: |
          git config user.email github-actions[bot]@users.noreply.github.com
          git config user.name github-actions[bot]

      - name: Commit changes
        run: |
          git add .
          git commit -m "style: format scripts" || exit 0
          git pull --rebase --autostash
          git push
