name: Patch

on:
  workflow_call:
    inputs:
      message:
        type: string
        default: "chore: apply patch"
    secrets:
      token:
        required: false
      ssh-key:
        required: false

env:
  BRANCH: ${{ github.head_ref || github.ref_name }}

permissions:
  contents: write

jobs:
  push:
    runs-on: ubuntu-slim

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          show-progress: false
          token: ${{ secrets.token || github.token }}
          ssh-key: ${{ secrets.ssh-key }}
          ref: ${{ env.BRANCH }}

      - name: Download artifact
        uses: actions/download-artifact@v8.0.1
        with:
          pattern: diff-patch

      - name: Set Git config
        run: |
          git config user.email github-actions[bot]@users.noreply.github.com
          git config user.name github-actions[bot]

      - name: Commit changes
        env:
          MESSAGE: ${{ inputs.message }}
        run: |
          git apply diff.patch || true
          git commit -am "$MESSAGE" || true
          git pull --rebase origin "$BRANCH"
          git push origin "HEAD:$BRANCH"
