name: Keep Alive

on: workflow_call

permissions:
  contents: write

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          show-progress: false

      - name: Set Git config
        run: |
          git config user.email github-actions[bot]@users.noreply.github.com
          git config user.name github-actions[bot]

      - name: Push and revert dummy commit
        run: |
          [ $(( $(date +%s) - $(git show -s --format=%ct) )) -lt 2629746  ] && exit 0
          git commit --allow-empty -m "chore: keep alive commit"
          git push
          git reset HEAD^
          git push --force-with-lease
