name: Keep Alive

on: workflow_call

permissions:
  contents: write

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Set Git config
        run: |
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]

      - name: Push dummy commit
        run: |
          [ $(( $(date +%s) - $(git show -s --format=%ct) )) -lt 2629746  ] && exit 0
          git commit --allow-empty -m "chore: keep alive commit"
          git push

      - name: Remove dummy commit
        run: |
          git reset HEAD^
          git push --force-with-lease
