name: Python

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Semantic Python version'
        type: string
        required: false
        default: '*'
      disable-test:
        description: 'Disable tests if true'
        type: boolean
        required: false

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          show-progress: false

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: ${{ inputs.python-version }}
          cache: poetry

      - name: Install dependencies
        run: poetry install

      - name: Run linter
        run: poetry run pylint --recursive=y .

  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          show-progress: false

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: ${{ inputs.python-version }}
          cache: poetry

      - name: Install dependencies
        run: poetry install

      - name: Run type checker
        run: poetry run pyright

  test:
    if: ${{ !inputs.disable-test }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          show-progress: false

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: ${{ inputs.python-version }}
          cache: poetry

      - name: Install dependencies
        run: poetry install

      - name: Test
        run: poetry run pytest
