name: Python

on:
  workflow_call:
    inputs:
      runs-on:
        description: 'Runner operating system'
        type: string
        default: ubuntu-latest
      python-version:
        description: 'Semantic Python version'
        type: string
        default: '*'
      disable-test:
        description: 'Disable tests if true'
        type: boolean

jobs:
  lint:
    runs-on: ${{ inputs.runs-on }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          show-progress: false

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: ${{ inputs.python-version }}
          cache: poetry

      - name: Install dependencies
        run: poetry install

      - name: Run linter
        run: poetry run ruff check

  type-check:
    runs-on: ${{ inputs.runs-on }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          show-progress: false

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: ${{ inputs.python-version }}
          cache: poetry

      - name: Install dependencies
        run: poetry install

      - name: Run type checker
        run: poetry run pyright

  test:
    if: ${{ !inputs.disable-test }}
    runs-on: ${{ inputs.runs-on }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          show-progress: false

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: ${{ inputs.python-version }}
          cache: poetry

      - name: Install dependencies
        run: poetry install

      - name: Test
        run: poetry run pytest
