name: Deploy

on:
  workflow_call:
    inputs:
      dockerfile:
        description: "Path to Dockerfile"
        type: string
        default: Dockerfile
    secrets:
      token:
        description: "A Hugging Face API token"
        required: true

permissions: {}
concurrency: ${{ github.workflow }}-${{ github.ref }}
env:
  DOCKERFILE_PATH: ${{ inputs.dockerfile }}

jobs:
  download:
    runs-on: ubuntu-slim
    permissions:
      contents: read

    steps:
      - name: Download Dockerfile from GitHub
        env:
          GH_TOKEN: ${{ github.token }}
        run: >-
          curl "https://raw.githubusercontent.com/$GITHUB_REPOSITORY_OWNER/${GITHUB_REPOSITORY#*/}/$GITHUB_REF_NAME/$DOCKERFILE_PATH"
          --header "Authorization: token $GH_TOKEN"
          --output "$DOCKERFILE_PATH"
          --create-dirs

      - name: Upload Dockerfile
        uses: actions/upload-artifact@v7.0.0
        with:
          name: dockerfile
          path: ${{ env.DOCKERFILE_PATH }}

  deploy:
    needs: download
    runs-on: ubuntu-slim
    environment:
      name: production
      url: https://huggingface.co/spaces/${{ github.repository }}

    steps:
      - name: Set Git config
        run: |
          git config http.extraHeader "Authorization: Bearer $HF_TOKEN"
          git config user.email github-actions[bot]@users.noreply.github.com
          git config user.name github-actions[bot]

      - name: Checkout Hugging Face repository
        run: git clone "https://huggingface.co/spaces/$GITHUB_REPOSITORY_OWNER/${GITHUB_REPOSITORY#*/}" .
        env:
          HF_TOKEN: ${{ secrets.token }}

      - name: Download updated Dockerfile
        uses: actions/download-artifact@v8.0.1
        with:
          name: dockerfile

      - name: Push to Hugging Face Spaces
        env:
          MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          git add "$DOCKERFILE_PATH"
          git commit --amend -m "$MESSAGE"
          git push --force-with-lease
