name: Warm

on:
  workflow_call:
    secrets:
      token:
        description: "A Hugging Face API token"
    inputs:
      path:
        description: "Path"
        type: string
        default: ""

permissions: {}
env:
  REPOSITORY_NAME: ${{ github.event.repository.name }}
  HF_TOKEN: ${{ secrets.token }}

jobs:
  warm:
    runs-on: ubuntu-slim

    steps:
      - name: Set cURL header
        run: echo "$CURL_HEADER" > ~/.curlrc
        env:
          CURL_HEADER: "-H Authorization: Bearer ${{ env.HF_TOKEN }}"

      - name: cURL the API
        run: curl -f "https://$GITHUB_REPOSITORY_OWNER-$REPOSITORY_NAME.hf.space$QUERY_PATH"
        env:
          QUERY_PATH: ${{ inputs.path }}

      - name: Restart on failure
        if: failure()
        run: curl -X POST "https://huggingface.co/api/spaces/$GITHUB_REPOSITORY/restart"
