name: uv

on:
  workflow_call:
    inputs:
      runs-on:
        description: 'Runner operating system'
        type: string
        default: ubuntu-latest
      recursive-clone:
        description: 'Recursively clone repository'
        type: boolean
      python-version:
        description: 'Semantic Python version'
        type: string
      disable-lint:
        description: 'Disable linting if true'
        type: boolean
      disable-type-check:
        description: 'Disable type checking if true'
        type: boolean
      disable-test:
        description: 'Disable tests if true'
        type: boolean
      install-project:
        description: 'Install the project if true'
        type: boolean
      working-directory:
        description: 'Working directory for the workflow'
        type: string
        default: .

env:
  UV_LINK_MODE: hardlink
  UV_LOCKED: 1

jobs:
  lint:
    if: ${{ !inputs.disable-lint }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0
        with:
          show-progress: false
          submodules: ${{ inputs.recursive-clone }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7.1.0
        with:
          python-version: ${{ inputs.python-version }}
          cache-dependency-glob: '**/uv.lock'

      - name: Run linter
        run: uvx ruff check --diff

  type-check:
    if: ${{ !inputs.disable-type-check }}
    runs-on: ${{ inputs.runs-on }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0
        with:
          show-progress: false
          submodules: ${{ inputs.recursive-clone }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7.1.0
        with:
          python-version: ${{ inputs.python-version }}
          cache-dependency-glob: '**/uv.lock'

      - name: Run type checker
        run: uv run pyright

  test:
    if: ${{ !inputs.disable-test }}
    runs-on: ${{ inputs.runs-on }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0
        with:
          show-progress: false
          submodules: ${{ inputs.recursive-clone }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7.1.0
        with:
          python-version: ${{ inputs.python-version }}
          cache-dependency-glob: '**/uv.lock'

      - name: Run test(s)
        run: uv run pytest

  install:
    if: ${{ inputs.install-project }}
    runs-on: ${{ inputs.runs-on }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0
        with:
          show-progress: false
          submodules: ${{ inputs.recursive-clone }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7.1.0
        with:
            python-version: ${{ inputs.python-version }}
            activate-environment: true
            cache-dependency-glob: '**/uv.lock'

      - name: Install project
        run: uv pip install .


