name: Python

on:
  workflow_call:
    inputs:
      runs-on:
        description: 'Runner operating system'
        type: string
        default: ubuntu-latest
      python-version:
        description: 'Semantic Python version'
        type: string
      disable-test:
        description: 'Disable tests if true'
        type: boolean
      working-directory:
        description: 'Working directory for the workflow'
        type: string
        default: .

env:
  UV_LINK_MODE: hardlink
  UV_LOCKED: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          show-progress: false

      - name: Install uv
        uses: astral-sh/setup-uv@v6.4.3
        with:
          python-version: ${{ inputs.python-version }}
          cache-dependency-glob: '**/uv.lock'

      - name: Run linter
        run: uvx ruff check

  type-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          show-progress: false

      - name: Install uv
        uses: astral-sh/setup-uv@v6.4.3
        with:
          python-version: ${{ inputs.python-version }}
          cache-dependency-glob: '**/uv.lock'

      - name: Run type checker
        run: uv run pyright

  test:
    if: ${{ !inputs.disable-test }}
    runs-on: ${{ inputs.runs-on }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          show-progress: false

      - name: Install uv
        uses: astral-sh/setup-uv@v6.4.3
        with:
          python-version: ${{ inputs.python-version }}
          cache-dependency-glob: '**/uv.lock'

      - name: Run test(s)
        run: uv run pytest
